version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: Server/
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_URL=mongodb://mongo:27017/mydb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
